version: '3.8'

services:
  redis_db:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data 
    restart: unless-stopped

  bot:
    build: .
    environment:
      - REDIS_HOST=redis_db
    env_file:
      - .env 
    depends_on:
      - redis_db
    restart: unless-stopped

volumes:
  redis_data: