version: '3.8'

services:
  redis_db:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data 
    restart: unless-stopped

  bot:
    build: .
    environment:
      - VK_TOKEN=${VK_TOKEN}
      - API_URL=${API_URL}
      - REDIS_HOST=redis_db
    depends_on:
      - redis_db
    volumes:
      - ./logs:/apps/logs
    restart: unless-stopped

volumes:
  redis_data: